// Code generated by protoc-gen-go. DO NOT EDIT.
// source: test/common/common.proto

package common // import "github.com/altipla-consulting/king/test/common"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_common_d2f05e93b864c109, []int{0}
}
func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (dst *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(dst, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

func init() {
	proto.RegisterType((*Empty)(nil), "king.common.Empty")
}

func init() { proto.RegisterFile("test/common/common.proto", fileDescriptor_common_d2f05e93b864c109) }

var fileDescriptor_common_d2f05e93b864c109 = []byte{
	// 105 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x28, 0x49, 0x2d, 0x2e,
	0xd1, 0x4f, 0xce, 0xcf, 0xcd, 0xcd, 0xcf, 0x83, 0x52, 0x7a, 0x05, 0x45, 0xf9, 0x25, 0xf9, 0x42,
	0xdc, 0xd9, 0x99, 0x79, 0xe9, 0x7a, 0x10, 0x21, 0x25, 0x76, 0x2e, 0x56, 0xd7, 0xdc, 0x82, 0x92,
	0x4a, 0x27, 0x83, 0x28, 0xbd, 0xf4, 0xcc, 0x92, 0x8c, 0xd2, 0x24, 0x90, 0x8c, 0x7e, 0x62, 0x4e,
	0x49, 0x66, 0x41, 0x4e, 0xa2, 0x6e, 0x72, 0x7e, 0x5e, 0x71, 0x69, 0x4e, 0x49, 0x66, 0x5e, 0xba,
	0x3e, 0x48, 0x97, 0x3e, 0x92, 0xa1, 0x49, 0x6c, 0x60, 0xe3, 0x8c, 0x01, 0x01, 0x00, 0x00, 0xff,
	0xff, 0xfe, 0xa2, 0xd7, 0xca, 0x6a, 0x00, 0x00, 0x00,
}
